---
- name: DOMAIN
  hosts: apic
  connection: local
  gather_facts: False

  tasks:

    - name: Add a new physical domain
      cisco.aci.aci_domain:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        domain: DOM2-PD
        domain_type: phys
        state: present
