---
- name: TAG EPGS
  hosts: apic
  connection: local
  gather_facts: False

  tasks:

    - name: CSV TO DICTIONARY
      community.general.read_csv:
        path: epgs.csv
        key: key
      register: epgs

    - name: TAG EPGS ON AAEP
      cisco.aci.aci_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        path: /api/node/mo/uni/infra/attentp-{{ item.value.aaep }}/gen-default.json
        method: post
        content:
          {
  "infraGeneric": {
    "attributes": {
      "dn": "uni/infra/attentp-{{ item.value.aaep }}/gen-default",
      "name": "default",
      "status": "created,modified"
    },
    "children": [
      {
        "infraRsFuncToEpg": {
          "attributes": {
            "tDn": "uni/tn-{{ item.value.tenant }}/ap-{{ item.value.ap }}/epg-{{ item.value.epg }}",
            "status": "created,modified",
            "encap": "vlan-{{ item.value.vlan }}"
          },
          "children": []
        }
      }
    ]
  }
}
      loop: "{{ epgs.dict|dict2items }}"
